#+title: Задание на позицию ассистента аналитика
#+date: [2025-08-06]
#+OPTIONS: \n:t

* Вакансия

*"Ассистент аналитика / инженера данных"*.

Обязанности:

#+begin_quote
- Писать SQL-запросы;
- Настраивать пайплайны сбора и обработки данных;
- Визуализировать данные;
- Взаимодействовать с заказчиками по результатам проделанной работы.
#+end_quote

* Тестовое задание

#+begin_quote
Возьмите свою страницу Вконтакте, соберите по ней таблицу с датой постов и количеством лайков и напишите SQL-запросы, которые позволят ответить на вопрос: что больше всего влияет на количество лайков: время суток публикации, день недели или промежуток между постами.

В качестве ответа приложите таблицу в формате CSV, SQL-запросы с необходимыми пояснениями и выводом. Вместо своей страницы можно взять станицу друга, в любом случае укажите адрес страницы.
#+end_quote

* Мой комментарий

Так получилось, что я только после выполнения задания обратил внимание на то, что это позиция ассистента :) На само задание потратил где-то 4 часа и явно сделал больше, чем запрашивалось. Зато получил интересный опыт, и может быть потом сделаю отдельную аналитику для себя по постам Дурова в ВК.
